<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE museScore [

<!-- diminished symbol - uncomment one only
			"&#186;"			circle
			"_"					superscript "dim" glyph
-->
    <!ENTITY dim "&#186;">
<!--
    <!ENTITY dim "_">
-->
<!-- half-diminished symbol - uncomment one only
			"&#187;"			striked circle
			"}7b5"				superscript  m7b5
-->
    <!ENTITY half_dim "&#187;">
<!--
    <!ENTITY half_dim "}7b5">
-->

<!-- minor/major symbols - uncomment one each only
			"}"			MI New Real Book style
			"{"			MA New Real Book style
			"&#205;"	  superscript triangle for maj7
-->

    <!ENTITY min "}">
    <!ENTITY maj "{">
<!--
    <!ENTITY min "m">
    <!ENTITY maj "maj">
-->
    <!ENTITY maj7 "&#205;">
<!--
    <!ENTITY maj7 "maj7">
-->
    <!ENTITY sixnine   "&#37;">
    <!ENTITY sus "sus">
    <!ENTITY lyd "Lyd">
<!-- superscript bemol & sharp signs -->
    <!ENTITY t_bemol "&#223;">
    <!ENTITY t_sharp "?">
<!-- superscript add/omit glyphs -->
    <!ENTITY t_add "&#64;">
    <!ENTITY t_omit "&#59;">

    <!ENTITY t_aug "aug">
<!-- open/close superscript parenthesis for tensions. Define to empty string to hide -->
<!--
<!ENTITY t_open "">
<!ENTITY t_close "">
-->

<!ENTITY t_open "(">
<!ENTITY t_close ")">

<!-- vertically stacked tensions; 1st number on top -->
<!ENTITY t_55 "&#192;">
<!ENTITY t_95 "&#193;">
<!ENTITY t_115 "&#194;">
<!ENTITY t_135 "&#195;">
<!ENTITY t_99 "&#196;">
<!ENTITY t_119 "&#197;">
<!ENTITY t_139 "&#198;">
<!ENTITY t_1111 "&#199;">
<!ENTITY t_1311 "&#200;">
<!ENTITY t_1313 "&#201;">
<!ENTITY t_76 "&#203;">
<!ENTITY t_9 "&#206;">
<!ENTITY t_11 "&#207;">
<!ENTITY t_13 "&#208;">

<!-- vertically stacked alterations, 1st one on top, b=bemol, s=sharp, 0=blank -->
<!ENTITY t_b0 "&#223;">
<!ENTITY t_0b "&#224;">
<!ENTITY t_bb "&#225;">
<!ENTITY t_sb "&#226;">
<!ENTITY t_0s "&#227;">
<!ENTITY t_bs "&#228;">
<!ENTITY t_ss "&#229;">

<!ELEMENT chord ( render ) >
<!ATTLIST chord id NMTOKEN #REQUIRED >

<!ELEMENT font EMPTY >
<!ATTLIST font id NMTOKEN #REQUIRED >

<!ELEMENT museScore ( font, renderRoot, renderBase, chord+ ) >
<!ATTLIST museScore version NMTOKEN #REQUIRED >

<!ELEMENT render ( #PCDATA ) >

<!ELEMENT renderBase ( #PCDATA ) >

<!ELEMENT renderRoot ( #PCDATA ) >
]>
<museScore version="1.11">

<!--
=====================================================================
    MuseScore
    Linux Music Score Editor
    $Id: mscore.cpp 1850 2009-05-25 07:44:35Z wschweer $

    Copyright (C) 2009 Werner Schweer and others

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

=====================================================================
    This file describes, how chord symbols are rendered
    in MuseScore
=====================================================================
    Adapted from stdchords.xml for the NewRealBook TTF font.
=====================================================================
-->

<!--
      Part I: font list
            associate symbols (code points) with names
      If no font family is given or font family is "default" then the
      configured text style font family is used.
-->

  <font id="0">   <!-- use chord name text style font -->
    </font>

<!--  <font id="1" family="Mscore1">
    <mag>1.2</mag>
    <sym code="0xe10d" name="b"/>   
    <sym code="0xe10c" name="#"/>
    </font>
-->

<!--
      Part II: chord list

         id       internal chord number
         render   this is a script which contains render commands
                  commands:
                        xxx         draw symbol name xxx
                        m:x:y       add x:y (point?) to current position
                        :push
                        :pop
                        :n          root or base note
                        :a          accidental
-->
 <renderRoot>:n :a</renderRoot>
  <renderBase>m:0:0 / m:1:10 :n :a</renderBase>
<!--
  <renderRoot>:n m:0:-1 :a m:.5:1</renderRoot>
  <renderBase>m:0:2 / :n :a</renderBase>
-->
  <chord id="1">
    <render></render>
    </chord>
  <chord id="2">
    <render>&maj;</render>
    </chord>
  <chord id="3">
    <render>5&t_bemol;</render>
    </chord>
  <chord id="4">
    <render>+</render>
    </chord>
  <chord id="5">
    <render>6</render>
    </chord>
  <chord id="6">
    <render>&maj7;</render>
    </chord>
  <chord id="7">
    <render>&maj;9</render>
    </chord>
  <chord id="8">
    <render>&maj;9&t_open;&t_sharp;11&t_close;</render>
    </chord>
<chord id="208">
    <render>&maj7;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="9">
<render>&maj;[&t_0s;&t_1311;]</render>
    </chord>
  <chord id="10">
    <render>&maj;13</render>
    </chord>
  <chord id="11">
    <render>&maj;9(no 3)</render>
    </chord>
  <chord id="12">
    <render>+</render>
    </chord>
  <chord id="13">
    <render>&maj7;&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="14">
    <render>&sixnine;</render>
    </chord>
  <chord id="15">
    <render>2</render>
    </chord>
  <chord id="16">
    <render>&min;</render>
    </chord>
  <chord id="17">
    <render>&min;+</render>
    </chord>
  <chord id="18">
    <render>&min;&maj7;</render>
    </chord>
  <chord id="19">
    <render>&min;7</render>
    </chord>
  <chord id="20">
    <render>&min;9</render>
    </chord>
  <chord id="21">
    <render>&min;11</render>
    </chord>
  <chord id="22">
    <render>&min;13</render>
    </chord>
  <chord id="23">
    <render>&min;6</render>
    </chord>
  <chord id="24">
    <render>&min;&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="25">
    <render>&min;7&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="26">
    <render>&min;&sixnine;</render>
    </chord>
  <chord id="27">
    <render>&lyd;</render>
    </chord>
  <chord id="28">
    <render>&maj;7&lyd;</render>
    </chord>
  <chord id="29">
    <render>&maj7;&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="32">
<render>&half_dim;</render>
    </chord>
  <chord id="33">
    <render>&dim;</render>
    </chord>
  <chord id="34">
    <render>&min;9&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="40">
    <render>5</render>
    </chord>
  <chord id="56">
    <render>7+</render>
    </chord>
  <chord id="57">
    <render>9+</render>
    </chord>
  <chord id="58">
    <render>13+</render>
    </chord>
  <chord id="59">
    <render>(blues)</render>
    </chord>
  <chord id="60">
    <render>7(Blues)</render>
    </chord>
  <chord id="64">
    <render>7</render>
    </chord>
  <chord id="65">
    <render>13</render>
    </chord>
  <chord id="66">
    <render>7&t_open;&t_bemol;13&t_close;</render>
    </chord>
  <chord id="67">
    <render>7&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="68">
    <render>13&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="69">
    <render>7[&t_bs;&t_1311;]</render>
    </chord>
  <chord id="70">
    <render>9</render>
    </chord>
  <chord id="72">
    <render>9&t_open;&t_bemol;13&t_close;</render>
    </chord>
  <chord id="73">
    <render>9&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="74">
    <render>13&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="75">
    <render>9[&t_bs;&t_1311;]</render>
    </chord>
  <chord id="76">
    <render>7&t_open;&t_bemol;9&t_close;</render>
    </chord>
  <chord id="77">
    <render>13&t_open;&t_bemol;9&t_close;</render>
    </chord>
  <chord id="78">
    <render>7[&t_bb;&t_139;]</render>
    </chord>
  <chord id="79">
    <render>7[&t_sb;&t_119;]</render>
    </chord>
  <chord id="80">
    <render>13[&t_sb;&t_119;]</render>
    </chord>
  <chord id="81">
    <render>7[&t_sb;&t_119;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="82">
    <render>7&t_open;&t_sharp;9&t_close;</render>
    </chord>
  <chord id="83">
    <render>13&t_open;&t_sharp;9&t_close;</render>
    </chord>
  <chord id="84">
    <render>7[&t_bs;&t_139;]</render>
    </chord>
  <chord id="85">
    <render>9&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="86">
    <render>13[&t_ss;&t_119;]</render>
    </chord>
  <chord id="87">
    <render>7[&t_ss;&t_119;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="88">
    <render>7&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="89">
    <render>13&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="90">
    <render>7[&t_bb;&t_135;]</render>
    </chord>
  <chord id="91">
    <render>9&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="92">
    <render>9[&t_bb;&t_135;]</render>
    </chord>
  <chord id="93">
    <render>7[&t_bb;&t_95;]</render>
    </chord>
  <chord id="94">
    <render>13[&t_bb;&t_95;]</render>
    </chord>
  <chord id="95">
    <render>7[&t_bb;&t_95;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="96">
    <render>7[&t_sb;&t_95;]</render>
    </chord>
  <chord id="97">
    <render>13[&t_sb;&t_95;]</render>
    </chord>
  <chord id="98">
    <render>7[&t_sb;&t_95;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="99">
    <render>7&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="100">
    <render>13&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="101">
    <render>7[&t_ss;&t_115;]</render>
    </chord>
  <chord id="102">
    <render>13[&t_ss;&t_115;]</render>
    </chord>
  <chord id="103">
    <render>9&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="104">
    <render>9[&t_ss;&t_115;]</render>
    </chord>
  <chord id="105">
    <render>7[&t_bs;&t_95;]</render>
    </chord>
  <chord id="106">
    <render>13[&t_bs;&t_95;]</render>
    </chord>
  <chord id="107">
    <render>7[&t_bs;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="108">
    <render>[&t_0s;&t_135;|&t_sb;&t_119;]</render>
    </chord>
  <chord id="109">
    <render>7[&t_ss;&t_95;]</render>
    </chord>
  <chord id="110">
    <render>13[&t_ss;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="111">
    <render>7[&t_ss;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="112">
    <render>13[&t_ss;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="113">
    <render>7`</render>
    </chord>
  <chord id="128">
    <render>7&sus;</render>
    </chord>
  <chord id="129">
    <render>13&sus;</render>
    </chord>
  <chord id="130">
    <render>7&sus;&t_open;&t_bemol;13&t_close;</render>
    </chord>
  <chord id="131">
    <render>7&sus;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="132">
    <render>13&sus;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="133">
    <render>7&sus;[&t_bs;&t_1311;]</render>
    </chord>
  <chord id="134">
    <render>9&sus;</render>
    </chord>
  <chord id="135">
    <render>9&sus;&t_open;&t_bemol;13&t_close;</render>
    </chord>
  <chord id="136">
    <render>9&sus;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="137">
    <render>13&sus;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="138">
    <render>13&sus;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="139">
    <render>9&sus;[&t_bs;&t_1311;]</render>
    </chord>
  <chord id="140">
    <render>7&sus;&t_open;&t_bemol;9&t_close;</render>
    </chord>
  <chord id="141">
    <render>13&sus;&t_open;&t_bemol;9&t_close;</render>
    </chord>
  <chord id="142">
    <render>7&sus;[&t_bb;&t_139;]</render>
    </chord>
  <chord id="143">
    <render>7&sus;[&t_sb;&t_119;]</render>
    </chord>
  <chord id="144">
    <render>13&sus;[&t_sb;&t_119;]</render>
    </chord>
  <chord id="145">
    <render>7&sus;[&t_sb;&t_119;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="146">
    <render>7&sus;&t_open;&t_sharp;9&t_close;</render>
    </chord>
  <chord id="147">
    <render>13&sus;&t_open;&t_sharp;9&t_close;</render>
    </chord>
  <chord id="148">
    <render>7&sus;[&t_bs;&t_139;]</render>
    </chord>
  <chord id="149">
    <render>9&sus;&t_open;&t_sharp;11&t_close;</render>
    </chord>
  <chord id="150">
    <render>13&sus;[&t_ss;&t_119;]</render>
    </chord>
  <chord id="151">
    <render>7&sus;[&t_ss;&t_119;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="152">
    <render>7&sus;&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="153">
    <render>13&sus;&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="154">
    <render>7&sus;[&t_bb;&t_135;]</render>
    </chord>
  <chord id="155">
    <render>9&sus;&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="156">
    <render>9&sus;[&t_bb;&t_135;]</render>
    </chord>
  <chord id="157">
    <render>7&sus;[&t_bb;&t_95;]</render>
    </chord>
  <chord id="158">
    <render>13&sus;[&t_bb;&t_95;]</render>
    </chord>
  <chord id="159">
    <render>7&sus;[&t_bb;&t_95;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="160">
    <render>7&sus;[&t_sb;&t_95;]</render>
    </chord>
  <chord id="161">
    <render>13&sus;[&t_sb;&t_95;]</render>
    </chord>
  <chord id="162">
    <render>7&sus;[&t_sb;&t_95;|&t_0b;&t_13;]</render>
    </chord>
  <chord id="163">
    <render>7&sus;&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="164">
    <render>13&sus;&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="165">
    <render>7&sus;[&t_ss;&t_115;]</render>
    </chord>
  <chord id="166">
    <render>13&sus;[&t_ss;&t_115;]</render>
    </chord>
  <chord id="167">
    <render>9&sus;&t_open;&t_sharp;5&t_close;</render>
    </chord>
  <chord id="168">
    <render>9&sus;[&t_ss;&t_115;]</render>
    </chord>
  <chord id="169">
    <render>7&sus;[&t_bs;&t_95;]</render>
    </chord>
  <chord id="170">
    <render>13&sus;[&t_bs;&t_95;]</render>
    </chord>
  <chord id="171">
    <render>7&sus;[&t_bs;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="172">
    <render>13&sus;[&t_bs;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="173">
    <render>7&sus;[&t_ss;&t_95;]</render>
    </chord>
  <chord id="174">
    <render>13&sus;[&t_ss;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="175">
    <render>7&sus;[&t_ss;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="176">
    <render>13&sus;[&t_ss;&t_95;|&t_0s;&t_11;]</render>
    </chord>
  <chord id="177">
    <render>4</render>
    </chord>
  <chord id="184">
    <render>&sus;</render>
    </chord>
  <chord id="185">
    <render>&dim;7</render>
    </chord>
  <chord id="186">
    <render>&sus;2</render>
    </chord>
  <chord id="187">
    <render>&min;&t_open;&t_add;&t_bemol;13&t_close;</render>
    </chord>
  <chord id="188">
    <render>&t_open;&t_sharp;13&t_close;</render>
    </chord>
  <chord id="189">
    <render>[&t_add;|&t_ss;&t_1311;]</render>
    </chord>
  <chord id="190">
    <render>&t_open;&t_add;&t_sharp;13&t_close;</render>
    </chord>
  <chord id="191">
    <render>6&t_open;&t_add;9&t_close;</render>
    </chord>
  <chord id="192">
    <render>&sus;4</render>
    </chord>
  <chord id="193">
    <render>11</render>
    </chord>
  <chord id="194">
    <render>&maj;11</render>
    </chord>
  <chord id="195">
    <render>Tristan</render>
    </chord>
  <chord id="196">
    <render>&min;7&t_open;&t_add;11&t_close;</render>
    </chord>
  <chord id="197">
    <render>&maj;7&t_open;&t_add;13&t_close;</render>
    </chord>
  <chord id="198">
    <render>&min;&t_open;&t_add;9&t_close;</render>
    </chord>
  <chord id="199">
    <render>&min;9&maj;7</render>
    </chord>
  <chord id="200">
    <render>5</render>
    </chord>
  <chord id="201">
    <render>&min;11&t_open;&t_bemol;5&t_close;</render>
    </chord>
  <chord id="202">
    <render>&dim;7&t_open;&t_add;&t_sharp;7&t_close;</render>
    </chord>
  <chord id="203">
    <render>[&t_0s;&t_95;]</render>
    </chord>
  <chord id="204">
    <render>&t_open;&t_omit;5&t_close;</render>
    </chord>
  <chord id="205">
    <render>&t_aug;7</render>
    </chord>
  <chord id="206">
    <render>&t_aug;9</render>
    </chord>
  <chord id="207">
    <render>&t_aug;13</render>
    </chord>
</museScore>
